// Builds the responsive WebP variants that next/image serves through image-loader.ts.
// Sources live in assets/images/ so Next never copies the originals into out/.
// Run via `npm run images`; `npm run dev` and `npm run build` trigger it automatically.
// Pass --check to verify without writing (used in CI to catch a stale image-manifest.ts).

import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

let sharp;
try {
  sharp = (await import('sharp')).default;
} catch {
  console.error('sharp is required to build images. Run `npm install`. If your CI uses --omit=optional, drop that flag.');
  process.exit(1);
}

const root = path.resolve(import.meta.dirname, '..');
const SRC_ROOT = path.join(root, 'assets/images');
const OUT_ROOT = path.join(root, 'public/images/_gen');
const MANIFEST = path.join(root, 'image-manifest.ts');
const check = process.argv.includes('--check');

// Must stay in sync with images.deviceSizes ∪ images.imageSizes in next.config.ts,
// otherwise next/image asks the loader for widths that were never generated.
const LADDER = [96, 128, 256, 384, 640, 828, 1080, 1440, 1920];

const WEBP_DEFAULT = { quality: 72, effort: 6, smartSubsample: true };
// Lossless alpha: the portrait is composited with a gradient mask, and a lossy
// alpha channel shows up as a halo against the hero gradient.
const WEBP_ALPHA = { quality: 82, effort: 6, smartSubsample: true, alphaQuality: 100 };
const OVERRIDES = { 'logo-nikolay.png': { quality: 90, effort: 6, alphaQuality: 100, smartSubsample: true } };

// Consumed outside next/image, so these need stable names a stylesheet or JSON-LD can hardcode.
const STABLE = [
  { src: 'air-waves.png', out: 'public/images/css/air-waves-1280.webp', width: 1280, format: 'webp', opts: { quality: 55, effort: 6 } },
  { src: 'logo-nikolay.png', out: 'public/images/og/logo-512.png', width: 512, format: 'png', opts: { compressionLevel: 9, palette: true, quality: 92 } },
];
// Referenced only from CSS, so it never needs a ladder or a manifest entry.
const LADDER_EXCLUDE = new Set(['air-waves.png']);

const walk = (dir, base = '') =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry =>
    entry.isDirectory() ? walk(path.join(dir, entry.name), `${base}${entry.name}/`) : [`${base}${entry.name}`]);

async function encode(builder, dest) {
  if (check) return;
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  // Encode to a temp name and rename, so an interrupted run cannot leave a
  // truncated file that the existsSync cache check would accept forever.
  const tmp = `${dest}.tmp`;
  await builder.toFile(tmp);
  fs.renameSync(tmp, dest);
}

const sources = walk(SRC_ROOT).filter(rel => /\.(png|jpe?g|webp)$/i.test(rel)).sort();
const manifest = {};
const expected = new Set();
let written = 0;

for (const rel of sources) {
  if (LADDER_EXCLUDE.has(rel)) continue;
  const abs = path.join(SRC_ROOT, rel);
  const meta = await sharp(abs).metadata();
  const opts = OVERRIDES[rel] ?? (meta.hasAlpha ? WEBP_ALPHA : WEBP_DEFAULT);

  // Never upscale: rungs below the intrinsic width, plus the intrinsic width itself
  // when it is within range, so a 2x viewport still gets every available pixel.
  const widths = LADDER.filter(width => width < meta.width);
  if (meta.width <= LADDER[LADDER.length - 1]) widths.push(meta.width);
  if (!widths.length) throw new Error(`No variants for ${rel} (width ${meta.width})`);

  const hash = createHash('sha256')
    .update(fs.readFileSync(abs))
    .update(JSON.stringify({ opts, format: 'webp', ladder: LADDER }))
    .digest('hex').slice(0, 8);

  const relNoExt = rel.replace(/\.[^.]+$/, '');
  const stem = `/images/_gen/${relNoExt}.${hash}`;
  manifest[`/images/${rel}`] = [stem, widths];

  for (const width of widths) {
    const dest = path.join(OUT_ROOT, `${relNoExt}.${hash}.${width}.webp`);
    expected.add(dest);
    if (fs.existsSync(dest)) continue;
    written += 1;
    await encode(sharp(abs).rotate().resize({ width, withoutEnlargement: true, fit: 'inside', kernel: 'lanczos3' }).webp(opts), dest);
  }
}

for (const { src, out, width, format, opts } of STABLE) {
  const dest = path.join(root, out);
  const pipeline = sharp(path.join(SRC_ROOT, src)).rotate().resize({ width, withoutEnlargement: true, fit: 'inside', kernel: 'lanczos3' });
  if (fs.existsSync(dest)) continue;
  written += 1;
  await encode(format === 'png' ? pipeline.png(opts) : pipeline.webp(opts), dest);
}

// Drop variants left behind by an earlier hash so stale encodes never accumulate.
let pruned = 0;
if (fs.existsSync(OUT_ROOT)) {
  for (const rel of walk(OUT_ROOT)) {
    const abs = path.join(OUT_ROOT, rel);
    if (expected.has(abs)) continue;
    pruned += 1;
    if (!check) fs.rmSync(abs);
  }
}

const body = `// GENERATED by scripts/generate-images.mjs. Do not edit.
// Maps the original public path of every image to its generated variants.
const manifest: Record<string, [stem: string, widths: number[]]> = {
${Object.entries(manifest).map(([key, [stem, widths]]) => `  ${JSON.stringify(key)}: [${JSON.stringify(stem)}, [${widths.join(', ')}]],`).join('\n')}
};
export default manifest;
`;

const current = fs.existsSync(MANIFEST) ? fs.readFileSync(MANIFEST, 'utf8') : '';
if (check) {
  const missing = [...expected].filter(dest => !fs.existsSync(dest));
  if (body !== current) { console.error('image-manifest.ts is stale. Run `npm run images` and commit the result.'); process.exit(1); }
  if (missing.length) { console.error(`Missing ${missing.length} generated variants. Run \`npm run images\`.`); process.exit(1); }
  console.log(`images: ok (${expected.size} variants, ${sources.length} sources)`);
} else {
  if (body !== current) fs.writeFileSync(MANIFEST, body);
  console.log(`images: ${expected.size} variants from ${sources.length} sources (${written} encoded, ${pruned} pruned)`);
}
