'use client';
import { useLocale } from "../i18n/LocaleProvider";
import { useState, type FormEvent } from 'react';
import Image from 'next/image';
import SiteHeader from '../components/SiteHeader';
import ProcessJourney from '../components/ProcessJourney';
import MotionEffects from '../components/MotionEffects';
import { AirVent, ArrowLeft, ArrowUp, Award, BadgeCheck, Building2, Check, ChevronDown, ClipboardCheck, Droplets, Fan, House, Leaf, Menu, MessageCircle, Phone, Power, Send, ShieldCheck, Snowflake, Sparkles, Volume2, Wind, Wrench, X } from 'lucide-react';
const PHONE = '052-332-2821';
const WHATSAPP = 'https://wa.me/972523322821';
function Brand() { const { t, url } = useLocale(); return <a className="brand brand-logo" href={url("/")} aria-label={t("ניקולאי — לעמוד הראשי")}><Image src="/images/logo-nikolay.png" alt={t("ניקולאי מערכות מיזוג אוויר")} width={356} height={380} priority/></a>; }
function WhatsApp({ children, className = '' }: {
    children?: React.ReactNode;
    className?: string;
}) { const { t } = useLocale(); return <a className={`button whatsapp ${className}`} href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle size={20}/>{children || t("שלחו הודעה")}</a>; }
function Heading({ eyebrow, title, description }: {
    eyebrow: string;
    title: string;
    description?: string;
}) { return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>; }
export default function Home() {
    const { t, url } = useLocale();
    const services = [
        { title: t("תכנון והתקנה מקצועית"), description: t("מתאימים את מערכת המיזוג לחלל ולצרכים שלכם, מהתכנון ועד ההתקנה."), image: 'vrf.png', icon: AirVent },
        { title: t("מיזוג בתים ודירות"), description: t("פתרונות מיזוג לבית, תיקונים ותחזוקה שוטפת לנוחות בכל עונה."), image: 'home-ac.png', icon: House },
        { title: t("מערכות VRF ומיזוג לעסקים"), description: t("פתרונות למשרדים, מוסדות וחללים מסחריים, בהתאמה לכל פרויקט."), image: 'office-ac.png', icon: Building2 },
    ];
    const faqs = [
        { q: t("כמה זמן לוקחת התקנת מזגן?"), a: t("משך ההתקנה תלוי בסוג המזגן, בתשתית הקיימת ובמורכבות העבודה. לאחר שנכיר את החלל ואת סוג המערכת, נוכל לתת הערכת זמן ולתאם את ההתקנה בהתאם.") },
        { q: t("מה ההבדל בין מערכת VRF למזגן רגיל?"), a: t("מערכת VRF יכולה לחבר מספר יחידות פנימיות ליחידה חיצונית משותפת ולאפשר שליטה נפרדת בחללים. הבחירה בין המערכות תלויה בגודל המבנה, בצרכים ובתקציב.") },
        { q: t("האם אפשר להזמין גם תיקון ותחזוקה?"), a: t("כן. אפשר לפנות לגבי תקלה, ירידה בביצועים או תחזוקה למערכת קיימת. כדאי לציין את סוג המזגן ולתאר את התקלה, ואפשר לצרף תמונה בוואטסאפ.") },
        { q: t("איך בוחרים מערכת מיזוג לבית או לעסק?"), a: t("מתחילים מהחלל: שטח, חלוקה לחדרים, כיווני שמש, בידוד ואופי השימוש. בשיחה נבין את הצרכים ונבדוק אילו פתרונות מתאימים לכם.") },
    ];
    const quickIssues = [
        { id: 'cooling', label: t("לא מקרר מספיק"), icon: Snowflake, title: t("המזגן עובד, אבל החדר לא מתקרר"), text: t("זה יכול לנבוע ממסננים מלוכלכים, הגדרה לא נכונה, מחסור בגז או תקלה אחרת. נתחיל בכמה פרטים קצרים כדי להבין אם נדרש ביקור."), tip: t("בדקו שהמזגן על מצב קירור ושהמסננים נקיים.") },
        { id: 'water', label: t("מטפטף מים"), icon: Droplets, title: t("יש נזילה או טפטוף מהמזגן"), text: t("נזילה יכולה להיגרם מסתימה בניקוז, התקנה לא מאוזנת או הצטברות לכלוך. מומלץ לא להתעלם כדי למנוע נזק לקיר או לריהוט."), tip: t("כבו את המזגן אם המים מתקרבים לשקע או לחיבור חשמלי.") },
        { id: 'noise', label: t("עושה רעש"), icon: Volume2, title: t("המזגן משמיע רעש חריג"), text: t("רעש חדש יכול להגיע מהיחידה הפנימית, מהמאוורר או מהיחידה החיצונית. סרטון קצר יעזור לזהות את מקור הרעש לפני ההגעה."), tip: t("צלמו סרטון קצר שבו שומעים את הרעש ושלחו אותו בוואטסאפ.") },
        { id: 'power', label: t("לא נדלק"), icon: Power, title: t("המזגן לא מגיב או לא נדלק"), text: t("לפעמים מדובר בשלט או בסוללות, ולעיתים באספקת החשמל או בתקלה במערכת. נבדוק יחד מה כבר ניסיתם ונכוון אתכם להמשך."), tip: t("נסו סוללות חדשות בשלט ובדקו אם מפסק המזגן בלוח החשמל קפץ.") },
        { id: 'smell', label: t("ריח לא נעים"), icon: Wind, title: t("יוצא מהמזגן ריח לא נעים"), text: t("ריח עשוי להעיד על הצטברות לחות ולכלוך במסננים או בתוך היחידה. ניקוי מקצועי יכול לשפר את איכות האוויר ואת פעולת המזגן."), tip: t("נקו רק את המסננים הנשלפים לפי הוראות היצרן; טיפול פנימי משאירים לאיש מקצוע.") },
    ];
    const [openFaq, setOpenFaq] = useState<number | null>(0);
    const [formStatus, setFormStatus] = useState('');
    const [guide, setGuide] = useState<number | null>(null);
    const [selectedIssue, setSelectedIssue] = useState('cooling');
    const issue = quickIssues.find(item => item.id === selectedIssue) ?? quickIssues[0];
    function contact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const message = t("שלום ניקולאי, אשמח לשמוע פרטים.\nשם: {0}\nטלפון: {1}\nנושא: {2}\n{3}", data.get('name'), data.get('phone'), data.get('service'), data.get('message') || ''); const link = document.createElement('a'); link.href = `${WHATSAPP}?text=${encodeURIComponent(message)}`; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.click(); setFormStatus(t("הפרטים הועברו לחלון WhatsApp. יש ללחוץ שם על שליחה כדי להשלים את הפנייה.")); }
    return <>
 <MotionEffects />
 <a href="#main" className="skip-link">{t("דלגו לתוכן")}</a>
 <SiteHeader/>
 <main id="main">
 <section className="hero" id="home"><Image src="/images/hero-background.png" alt="" fill priority sizes="100vw" className="hero-background"/><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow"><span className="tiny-line"/>{t("ניקולאי מערכות מיזוג אוויר")}</span><h1>{t("מיזוג חכם.")}<br />{t("עיצוב נקי.")}<br /><span>{t("שירות מקצועי.")}</span></h1><p>{t("מערכת מיזוג טובה מתחילה בתכנון נכון.")}<br />{t("תכנון, התקנה ושירות לבית ולעסק, עם עבודה מדויקת")}<br className="desktop-break"/>{t(" וליווי אישי מהשיחה הראשונה.")}</p><div className="hero-actions"><a className="button call" href="tel:0523322821"><Phone size={19}/><span dir="ltr">{PHONE}</span></a><WhatsApp className="white">{t("דברו איתנו בוואטסאפ")}</WhatsApp></div><span className="hero-signature">{t("תכנון מדויק. ביצוע מקצועי.")}</span></div><div className="hero-visual"><Image src="/images/nikolai-transparent.png" alt={t("ניקולאי, טכנאי מערכות מיזוג אוויר")} width={1192} height={1320} priority className="portrait"/><div className="temperature glass" aria-label={t("איור טמפרטורה 24 מעלות")}><div className="temperature-ring"><Snowflake size={28}/><strong dir="ltr">24°</strong></div><p>{t("נעים בבית.")}<br />{t("בכל עונה.")}</p><div className="temperature-icons"><House size={17}/><Leaf size={17}/><Fan size={17}/></div></div></div></div></section>
 <div className="container benefits glass">{[{ icon: ShieldCheck, title: t("שירות אישי ומקצועי"), text: t("ליווי לאורך כל הדרך") }, { icon: BadgeCheck, title: t("עבודה מדויקת"), text: t("תשומת לב לכל פרט") }, { icon: Sparkles, title: t("פתרון שמתאים לכם"), text: t("לבית, למשרד ולעסק") }].map(({ icon: Icon, title, text }) => <div key={title}><span className="icon-bubble"><Icon /></span><span><strong>{title}</strong><small>{text}</small></span></div>)}</div>
 <section id="services" className="section services container"><Heading eyebrow={t("השירותים שלנו")} title={t("פתרון מדויק לכל חלל")} description={t("מהמזגן בבית ועד מערכת המיזוג של העסק. אנחנו כאן בשבילכם.")}/><div className="service-grid">{services.map(({ title, description, image, icon: Icon }) => <article className="service-card glass" key={title}><div className="image-wrap"><Image src={`/images/${image}`} alt={title} fill sizes="(max-width: 700px) 100vw, 33vw"/></div><div className="card-body"><span className="service-icon"><Icon size={23}/></span><h3>{title}</h3><p>{description}</p><a href={`${WHATSAPP}?text=${encodeURIComponent(t("שלום ניקולאי, אשמח לפרטים לגבי {0}", title))}`} target="_blank" rel="noreferrer">{t("בואו נדבר ")}<ArrowLeft size={17}/></a></div></article>)}</div><div className="service-tags"><span><Wrench size={16}/>{t("תיקון ותחזוקה")}</span><span><ClipboardCheck size={16}/>{t("ייעוץ ותכנון")}</span><span><AirVent size={16}/>{t("מערכות VRF")}</span><span><Building2 size={16}/>{t("בתים, עסקים ומוסדות")}</span></div></section>
 <section className="section quick-diagnosis" id="quick-check"><div className="container"><Heading eyebrow={t("בדיקה מהירה")} title={t("מה המזגן עושה?")} description={t("בחרו את התופעה שמתארת הכי טוב את המצב ונעזור לכם להתקדם.")}/><div className="diagnosis-panel glass"><div className="issue-picker" role="group" aria-label={t("בחירת תקלה")}>{quickIssues.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={selectedIssue === id ? 'active' : ''} onClick={() => setSelectedIssue(id)} aria-pressed={selectedIssue === id}><Icon size={22}/><span>{label}</span></button>)}</div><div className="issue-result" aria-live="polite"><span className="result-icon"><issue.icon size={30}/></span><div><small>{t("הכוונה ראשונית")}</small><h3>{issue.title}</h3><p>{issue.text}</p><div className="issue-tip"><Check size={17}/><span>{issue.tip}</span></div><div className="diagnosis-actions"><a className="button whatsapp" href={`${WHATSAPP}?text=${encodeURIComponent(t("שלום ניקולאי, המזגן שלי {0}. אשמח להתייעץ ולבדוק אם צריך ביקור.", issue.label))}`} target="_blank" rel="noreferrer"><MessageCircle size={19}/>{t("שליחת התקלה לניקולאי")}</a><a className="diagnosis-call" href="tel:0523322821"><Phone size={18}/>{t("מעדיפים לדבר?")}</a></div><em>{t("המידע הוא הכוונה כללית ואינו מחליף בדיקה מקצועית.")}</em></div></div></div></div></section>
 <section id="about" className="section about-section"><div className="container about-grid"><div className="about-photo"><Image src="/images/nikolai-hello.png" alt={t("ניקולאי, טכנאי מערכות מיזוג אוויר")} fill sizes="(max-width: 800px) 100vw, 50vw"/><div className="photo-label glass"><Wrench size={20}/><span>{t("מקצוענות בכל פרט")}</span></div></div><div className="about-copy"><span className="eyebrow">{t("נעים להכיר")}</span><h2>{t("היי, אני ")}<span>{t("ניקולאי אנדריצ׳נקו")}</span></h2><p>{t("בעל ידע ומומחיות בהנדסת מיזוג אוויר ותכנון מערכות מיזוג בבית ובתעשייה. אני מתמחה בייעוץ אישי וליווי מלא מהתכנון ועד לביצוע, כולל שיווק והתקנת מזגנים עם התייחסות רב־מערכתית.")}</p><p>{t("אשל המיזוג מספקת פתרונות מקיפים ושירות איכותי כדי להפוך את ביתכם או משרדכם לנעים יותר.")}</p><div className="about-checks"><span><Check size={18}/>{t("הנדסת מיזוג ותכנון מערכות")}</span><span><Check size={18}/>{t("ליווי אישי מהתכנון ועד לביצוע")}</span><span><Check size={18}/>{t("פתרונות לבית, לתעשייה ולמשרד")}</span></div><div className="about-actions"><a href={url("#contact")} className="button call">{t("נמצא את הפתרון שלכם ")}<ArrowLeft size={18}/></a><a href={url("/certificates")} className="text-link"><Award size={18}/>{t("לתעודות והסמכות")}</a></div></div></div></section>
 <section id="projects" className="section container"><Heading eyebrow={t("פרויקטים נבחרים")} title={t("מיזוג שמשתלב בחיים שלכם")} description={t("הצצה לסוגי העבודות והמערכות שאנחנו מבצעים.")}/><div className="project-grid">{[{ title: t("בתים פרטיים ודירות"), sub: t("נוחות בכל חדר"), image: 'home-ac.png' }, { title: t("משרדים ועסקים"), sub: t("סביבת עבודה נעימה"), image: 'office-ac.png' }, { title: t("מבנים ומערכות גדולות"), sub: t("מערכות VRF"), image: 'vrf.png' }].map(item => <a href={url("/projects")} key={item.title} className="project-card"><Image src={`/images/${item.image}`} alt={item.title} fill sizes="(max-width: 700px) 100vw, 33vw"/><div><small>{item.sub}</small><h3>{item.title}</h3><span>{t("לצפייה בפרויקטים ")}<ArrowLeft size={16}/></span></div></a>)}</div><div className="section-action"><a className="button call" href={url("/projects")}>{t("לכל הפרויקטים ")}<ArrowLeft size={18}/></a></div><p className="image-note">{t("בשלב זה מוצגות תמונות לדוגמה, וניתן להחליפן בהמשך בתמונות מהשטח.")}</p></section>
 <section className="section credentials-teaser"><div className="container credentials-panel"><div><span className="eyebrow">{t("מקצועיות שאפשר לראות")}</span><h2>{t("תעודות והסמכות מקצועיות")}</h2><p>{t("ריכזנו במקום אחד את ההכשרות והתעודות המקצועיות. לחצו על כל תעודה כדי להציג אותה בגודל מלא.")}</p><a href={url("/certificates")} className="button call">{t("לצפייה בתעודות ")}<ArrowLeft size={18}/></a></div><div className="credentials-stack"><Image src="/images/certificate-2.png" alt={t("תעודה מקצועית לדוגמה")} width={590} height={600}/><Image src="/images/certificate-1.png" alt={t("תעודה מקצועית לדוגמה")} width={590} height={600}/></div></div></section>
 <ProcessJourney/>
 <section id="tips" className="section container tips-section"><div className="tips-intro"><span className="eyebrow">{t("טיפים ומידע שימושי")}</span><h2>{t("מיזוג נכון מתחיל")}<br />{t("בבחירה נכונה.")}</h2><p>{t("כמה דברים שכדאי לדעת לפני שבוחרים ומתחזקים מערכת מיזוג.")}</p></div><div className="tips-grid">{[{ title: t("איך בוחרים מזגן שמתאים לבית?"), image: 'home-ac.png', text: t("כדאי לבחון את גודל החלל, כיווני השמש, הבידוד ואופן השימוש. מערכת גדולה יותר אינה תמיד הבחירה הנכונה. תכנון מקצועי עוזר להתאים את המערכת לצרכים ולאילוצי הבית.") }, { title: t("איך שומרים על המזגן לאורך זמן?"), image: 'nikolai-working.png', text: t("נקו מסננים בהתאם להוראות היצרן, שמרו על פתחי האוויר פנויים ושימו לב לרעשים חריגים או לירידה בביצועים. לפני ניקוי יש לכבות ולנתק את המכשיר לפי הוראות היצרן. עבודות חשמל וטיפול פנימי משאירים לאיש מקצוע.") }].map((tip, index) => <article className="tip-card glass" key={tip.title}><div className="tip-image"><Image src={`/images/${tip.image}`} alt="" fill sizes="(max-width: 700px) 100vw, 30vw"/></div><button aria-expanded={guide === index} onClick={() => setGuide(guide === index ? null : index)}>{tip.title}<ArrowLeft size={18}/></button><p className="tip-text" hidden={guide !== index}>{tip.text}</p></article>)}</div></section>
 <div className="container guide-link-strip"><div><ClipboardCheck size={26}/><span>{t("לפני שמזמינים טכנאי מזגנים")}</span></div><a className="text-link" href={url("/guide")}>{t("למדריך ולרשימת ההכנה")}<ArrowLeft size={18}/></a></div>
 <section id="faq" className="section faq-section"><div className="container narrow"><Heading eyebrow={t("שאלות נפוצות")} title={t("שאלתם? אנחנו כאן לענות.")}/><div className="faq-list">{faqs.map((faq, index) => <div key={faq.q} className={`faq-item glass ${openFaq === index ? 'active' : ''}`}><h3><button id={`question-${index}`} aria-expanded={openFaq === index} aria-controls={`answer-${index}`} onClick={() => setOpenFaq(openFaq === index ? null : index)}>{faq.q}<ChevronDown size={20}/></button></h3><div id={`answer-${index}`} role="region" aria-labelledby={`question-${index}`} hidden={openFaq !== index}><p>{faq.a}</p></div></div>)}</div></div></section>
 <section id="contact" className="section contact-section"><div className="container contact-panel glass"><div className="contact-copy"><span className="eyebrow">{t("בואו נדבר")}</span><h2>{t("צריכים פתרון")}<br /><span>{t("מיזוג מקצועי?")}</span></h2><p>{t("התקנה, תיקון, תחזוקה או תכנון מערכת חדשה —")}<br />{t("ספרו לנו על החלל ועל הצורך שלכם.")}</p><a className="contact-phone" dir="ltr" href="tel:0523322821"><Phone size={25}/>{PHONE}</a><a className="text-whatsapp" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle size={21}/>{t("אפשר גם ישירות בוואטסאפ")}</a></div><form onSubmit={contact}><div className="form-row"><label>{t("שם מלא")}<input name="name" autoComplete="name" placeholder={t("איך קוראים לכם?")} required maxLength={80}/></label><label>{t("טלפון")}<input name="phone" type="tel" inputMode="tel" dir="ltr" autoComplete="tel" placeholder="050-000-0000" required pattern="[+0-9() -]{8,20}" maxLength={20}/></label></div><label>{t("במה נוכל לעזור?")}<select name="service" defaultValue="" required><option value="" disabled>{t("בחרו נושא")}</option><option>{t("התקנת מזגן")}</option><option>{t("תיקון ותחזוקה")}</option><option>{t("מערכת VRF")}</option><option>{t("ייעוץ ותכנון")}</option><option>{t("פנייה כללית")}</option></select></label><label>{t("כמה מילים על הפנייה ")}<span className="optional">{t("(לא חובה)")}</span><textarea name="message" rows={3} maxLength={1500} placeholder={t("סוג החלל, המזגן או התקלה...")}/></label><button type="submit" className="button call submit">{t("ממשיכים לוואטסאפ ")}<Send size={18}/></button><small className="form-note">{t("הפרטים ייפתחו בהודעה מוכנה בוואטסאפ. השליחה מתבצעת על ידכם.")}</small><p role="status" className="form-status">{formStatus}</p></form></div></section>
 </main><footer><div className="container footer-top"><Brand /><nav aria-label={t("ניווט תחתון")}><a href={url("#services")}>{t("שירותים")}</a><a href={url("#about")}>{t("אודות")}</a><a href={url("#faq")}>{t("שאלות נפוצות")}</a><a href={url("#contact")}>{t("צור קשר")}</a></nav><a className="back-top" href={url("#home")} aria-label={t("חזרה לראש העמוד")}><ArrowUp size={21}/></a></div><div className="container footer-bottom"><small>© {new Date().getFullYear()}{t(" ניקולאי מערכות מיזוג אוויר")}</small><span>{t("תכנון, התקנה ושירות למערכות מיזוג")}</span></div></footer><div className="mobile-contact-dock" aria-label={t("יצירת קשר מהירה")}><a href="tel:0523322821"><Phone size={20}/><span>{t("חייגו עכשיו")}</span></a><a href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle size={20}/><span>WhatsApp</span></a></div><a className="floating-whatsapp" href={WHATSAPP} target="_blank" rel="noreferrer" aria-label={t("שלחו הודעה בוואטסאפ")}><MessageCircle size={28}/></a>
 </>;
}
